

public enum MessageType
{
    NEW_CLIENT_CONNECTION,
    SERVER_SCENE_CHANGE_WRITING_ROOM,
    SERVER_SCENE_CHANGE_STAGE,
    PLAYER_SETUP_RESPONSE,
    PLAYER_PUNCHLINE_RESPONSE,
    PLAYER_POINTS_SUBMISSION,
    SERVER_SETUP_REQUEST,
    SERVER_PUNCHLINE_REQUEST,
   

}
